export {HomePage} from './home'
export {LoginPage} from './auth'
export {EmployeesPage} from './employees'
export {CommonReferencePage} from './common-reference-page'
export {NotaryContollerPage} from './notary-controller-page'